import { firebaseConfig, appCheckConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js';
import { getAuth, onAuthStateChanged, signInAnonymously, OAuthProvider, signInWithPopup, signOut as firebaseSignOut } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import { getFirestore, collection, doc, addDoc, setDoc, updateDoc, getDocs, onSnapshot, query, orderBy, serverTimestamp, writeBatch } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { initializeAppCheck, ReCaptchaEnterpriseProvider } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-app-check.js';

const STAFF_DOMAIN='@bemidjistate.edu';
const configured=!!firebaseConfig.projectId && !String(firebaseConfig.projectId).includes('PASTE_');
let app=null, auth=null, fs=null, currentUser=null, staff=false, appCheckEnabled=false;
let machines=[], reports=[], repairs=[], tutorials=[];

const starterMachines=[
 {id:'laser-epilog-fusion-01',name:'Epilog Fusion Pro Laser',category:'Laser Cutter',room:'Maker Lab',manufacturer:'Epilog',model:'Fusion Pro',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'Epilog Laser Cutter'},
 {id:'cnc-shopbot-01',name:'ShopBot CNC Router',category:'CNC Router',room:'BH 126',manufacturer:'ShopBot',model:'PRTalpha',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'ShopBot CNC Router'},
 {id:'printer-afinia-h800-01',name:'Afinia H800 3D Printer',category:'3D Printer',room:'3D Print Lab',manufacturer:'Afinia',model:'H800',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'Afinia H800 3D Printer'},
 {id:'printer-hp-latex-01',name:'HP Latex Printer',category:'Large Format Printer',room:'Maker Lab',manufacturer:'HP',model:'Latex',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'HP Latex Printer'},
 {id:'cutter-kongsberg-01',name:'Kongsberg Cutter',category:'Digital Cutter',room:'Maker Lab',manufacturer:'Kongsberg',model:'',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'Kongsberg Cutter'},
 {id:'cutter-graphtec-01',name:'Graphtec Vinyl Cutter',category:'Vinyl Cutter',room:'Maker Lab',manufacturer:'Graphtec',model:'',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'Graphtec Vinyl Cutter'},
 {id:'dyesub-printer-01',name:'Dye-Sublimation Printer',category:'Dye Sublimation',room:'Maker Lab',manufacturer:'',model:'',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'Dye-Sublimation Printer'},
 {id:'waterjet-wazer-01',name:'Wazer Waterjet',category:'Waterjet',room:'Maker Lab',manufacturer:'Wazer',model:'',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:'Wazer Waterjet'}
];

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const toDate=v=>v?.toDate?v.toDate():v instanceof Date?v:new Date(v||Date.now());
const date=v=>toDate(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const totalRepair=r=>Number(r.partsCost||0)+Number(r.serviceCost||0);
const machine=id=>machines.find(m=>m.id===id)||{id,name:'Unknown Machine',room:'',tutorialEquipment:''};
const badge=v=>`<span class="badge ${String(v).toLowerCase().replaceAll(' ','')}">${esc(v)}</span>`;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function slug(s){return String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}

const titles={dashboard:['Dashboard','Lab equipment status, resources, issues, repairs, and costs.'],report:['Report a Problem','Submit a machine issue from a Linktree maintenance button or the app.'],tutorials:['Tutorials','Direct TAD tutorials for machines, software, and lab workflows.'],reports:['Reports','Review and manage issue history.'],machines:['Machines','Equipment inventory, maintenance links, and tutorials.'],costs:['Costs & Repairs','Track repair history and lifetime equipment costs.'],export:['Export / Backup','Download live records for Excel and archival.'],settings:['Settings','Firebase connection, staff access, and abuse protection.']};
function showView(v){if(!titles[v])v='dashboard';if(['reports','machines','costs','export'].includes(v)&&!staff){toast('Staff sign-in required');v='dashboard'}$$('.view').forEach(x=>x.classList.remove('active'));$(`#view-${v}`)?.classList.add('active');$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent=titles[v][0];$('#pageSubtitle').textContent=titles[v][1];$('.sidebar').classList.remove('open');if(v==='report'&&new URLSearchParams(location.search).has('machine'))history.replaceState(null,'',location.pathname+location.search+'#report');else history.replaceState(null,'',location.pathname+(location.search||'')+'#'+v)}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('#quickReport').onclick=()=>showView('report');$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');

async function loadTutorials(){tutorials=await fetch('./data/tutorials.json').then(r=>r.json());renderTutorialFilters();renderTutorials();renderPublicMachines();renderMachineResourcePanel()}
const tutorialEquipments=t=>[t.equipment,t.secondaryEquipment].filter(Boolean);
function renderTutorialFilters(){const types=[...new Set(tutorials.map(t=>t.type))].sort(), eq=[...new Set(tutorials.flatMap(t=>tutorialEquipments(t)))].sort();$('#tutorialType').innerHTML='<option value="All">All types</option>'+types.map(x=>`<option>${esc(x)}</option>`).join('');$('#tutorialEquipment').innerHTML='<option value="All">All equipment</option>'+eq.map(x=>`<option>${esc(x)}</option>`).join('')}
function renderTutorials(){const q=($('#tutorialSearch').value||'').toLowerCase(),type=$('#tutorialType').value||'All',eq=$('#tutorialEquipment').value||'All';const list=tutorials.filter(t=>(type==='All'||t.type===type)&&(eq==='All'||tutorialEquipments(t).includes(eq))&&(!q||[t.title,t.type,...tutorialEquipments(t),...t.tags].join(' ').toLowerCase().includes(q))).sort((a,b)=>a.title.localeCompare(b.title));$('#tutorialCount').textContent=`${list.length} tutorial${list.length===1?'':'s'} shown`;$('#tutorialGrid').innerHTML=list.map(t=>`<article class="tutorial-card"><div class="tutorial-meta">${esc(tutorialEquipments(t).join(' + ')||t.type)}${t.author?' · '+esc(t.author):''}</div><h4>${esc(t.title)}</h4><p>${esc(t.tags.join(' · ')||t.type)}</p><a class="btn primary small" href="${esc(t.url)}" target="_blank" rel="noopener">Open tutorial ↗</a></article>`).join('')||'<div class="empty">No tutorials match these filters.</div>'}
['tutorialSearch','tutorialType','tutorialEquipment'].forEach(id=>$(`#${id}`).addEventListener(id==='tutorialSearch'?'input':'change',renderTutorials));
function tutorialsForMachine(m){return tutorials.filter(t=>m.tutorialEquipment&&tutorialEquipments(t).includes(m.tutorialEquipment)).sort((a,b)=>a.title.localeCompare(b.title))}
function renderMachineResourcePanel(){const id=$('#reportMachine').value||new URLSearchParams(location.search).get('machine');const m=machine(id);if(!m.id){$('#machineResourcePanel').innerHTML='<p>Select a machine to see its direct tutorials.</p>';return}const ts=tutorialsForMachine(m);$('#machineResourcePanel').innerHTML=`<p><strong>${esc(m.name)}</strong><br>${esc(m.room||'Location not set')}</p><div class="tutorial-list">${ts.slice(0,12).map(t=>`<a class="tutorial-link" target="_blank" rel="noopener" href="${esc(t.url)}">${esc(t.title)} ↗</a>`).join('')||'<span class="row-meta">No equipment-specific tutorial mapped yet.</span>'}</div>${ts.length>12?`<p class="row-meta">${ts.length-12} more available on the Tutorials page.</p>`:''}`}

function renderStaffVisibility(){$$('.staff-only').forEach(el=>el.classList.toggle('hidden',!staff));$('#staffLogin').textContent=staff?(currentUser?.email||'Staff signed in'):'Staff sign in';$('#settingsLogin').classList.toggle('hidden',staff);$('#signOut').classList.toggle('hidden',!staff);$('#authStatus').textContent=staff?`Staff: ${currentUser.email}`:'Student reporting access'}
function renderConnection(){const b=$('#setupBanner');if(!configured){b.classList.remove('hidden');b.innerHTML='<strong>Firebase setup required:</strong> add this project’s Web App configuration to <code>firebase-config.js</code>, enable Firestore + Authentication, and deploy the included rules. This release is designed for the no-cost Spark plan; no billing account or Cloud Functions are required.';$('#connectionStatus').textContent='Firebase setup required';$('#firebaseInfo').innerHTML='<p>This release uses Firestore and Firebase Authentication on the <strong>Spark/no-cost plan</strong>. Complete <strong>FIREBASE-SETUP.md</strong>, then add App Check before public launch.</p>';return}if(!appCheckEnabled){b.classList.remove('hidden');b.innerHTML='<strong>Abuse protection not active yet:</strong> Firebase is connected, but App Check is not configured. Add your reCAPTCHA Enterprise site key in <code>firebase-config.js</code> and test App Check before enabling enforcement.'}else{b.classList.add('hidden')}$('#connectionStatus').textContent=appCheckEnabled?'● Firebase + App Check':'● Firebase connected';$('#firebaseInfo').innerHTML=`<p><strong>Project:</strong> ${esc(firebaseConfig.projectId)}</p><p>Live machine, report, repair, and cost records are stored in Cloud Firestore.</p><p><strong>Plan:</strong> Spark / no billing required for this release.</p><p><strong>App Check:</strong> ${appCheckEnabled?'configured in the web app':'site key still needed before public launch'}</p>`}

async function initFirebase(){if(!configured){renderConnection();machines=starterMachines;renderAll();return}app=initializeApp(firebaseConfig);const siteKey=appCheckConfig?.recaptchaEnterpriseSiteKey||'';if(siteKey&&!siteKey.includes('PASTE_')){initializeAppCheck(app,{provider:new ReCaptchaEnterpriseProvider(siteKey),isTokenAutoRefreshEnabled:true});appCheckEnabled=true}renderConnection();auth=getAuth(app);fs=getFirestore(app);onAuthStateChanged(auth,async user=>{currentUser=user;staff=!!(user?.email&&user.email.toLowerCase().endsWith(STAFF_DOMAIN)&&user.emailVerified);renderStaffVisibility();if(!user){try{await signInAnonymously(auth)}catch(e){console.error(e);toast('Student reporting sign-in could not start')}}subscribeData()})}
let subscribed=false;function subscribeData(){if(!fs||subscribed)return;subscribed=true;onSnapshot(collection(fs,'machines'),snap=>{machines=snap.docs.map(d=>({id:d.id,...d.data()}));renderAll()});if(staff){subscribeStaffCollections()}else{reports=[];repairs=[];renderAll()}}
let staffSubscribed=false;function subscribeStaffCollections(){if(staffSubscribed||!fs)return;staffSubscribed=true;onSnapshot(query(collection(fs,'reports'),orderBy('createdAt','desc')),snap=>{reports=snap.docs.map(d=>({id:d.id,...d.data()}));renderAll()});onSnapshot(query(collection(fs,'repairs'),orderBy('date','desc')),snap=>{repairs=snap.docs.map(d=>({id:d.id,...d.data()}));renderAll()})}
async function staffLogin(){if(!configured)return toast('Configure Firebase first');try{const result=await signInWithPopup(auth,new OAuthProvider('microsoft.com'));if(!result.user.email?.toLowerCase().endsWith(STAFF_DOMAIN)){await firebaseSignOut(auth);toast('Use a Bemidji State account for staff access')}else{staffSubscribed=false;subscribeStaffCollections();toast('Staff access enabled')}}catch(e){console.error(e);toast('Sign-in was not completed')}}
$('#staffLogin').onclick=staffLogin;$('#settingsLogin').onclick=staffLogin;$('#signOut').onclick=async()=>{await firebaseSignOut(auth);staffSubscribed=false;subscribed=false;reports=[];repairs=[];await signInAnonymously(auth);toast('Signed out')};

function renderReportForm(){const sel=$('#reportMachine'), current=sel.value, q=new URLSearchParams(location.search).get('machine');sel.innerHTML=machines.length?machines.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(m=>`<option value="${esc(m.id)}">${esc(m.name)}${m.room?' — '+esc(m.room):''}</option>`).join(''):'<option value="">No machines configured</option>';sel.value=q&&machines.some(m=>m.id===q)?q:(machines.some(m=>m.id===current)?current:(machines[0]?.id||''));renderMachineResourcePanel()}
$('#reportMachine').addEventListener('change',renderMachineResourcePanel);
$('#reportForm').onsubmit=async e=>{e.preventDefault();if(!configured||!fs)return toast('Firebase must be configured before reports can be submitted');if(!currentUser)return toast('Connecting to reporting service…');const machineId=$('#reportMachine').value;if(!machineId)return toast('Please choose a machine');const m=machine(machineId);const payload={machineId,createdAt:serverTimestamp(),urgency:$('#urgency').value,usable:$('#usable').value,issue:$('#issue').value.trim(),attempted:$('#attempted').value.trim(),contact:$('#contact').value.trim(),resource:$('#resource').value.trim(),status:'Open',machineNameSnapshot:m.name,roomSnapshot:m.room||'',submittedByUid:currentUser.uid,submittedByEmail:currentUser.email||''};try{const ref=await addDoc(collection(fs,'reports'),payload);e.target.reset();renderReportForm();toast(`Report ${ref.id.slice(0,8)} submitted`);showView('dashboard')}catch(err){console.error(err);toast('Report could not be submitted. Check Firebase rules/App Check configuration.')}};

function renderStats(){if(!staff)return;const open=reports.filter(r=>r.status!=='Resolved').length,down=new Set(reports.filter(r=>r.status!=='Resolved'&&r.usable==='No').map(r=>r.machineId)).size,year=new Date().getFullYear(),cost=repairs.filter(r=>toDate(r.date).getFullYear()===year).reduce((a,r)=>a+totalRepair(r),0),all=repairs.reduce((a,r)=>a+totalRepair(r),0);$('#statsGrid').innerHTML=[['Open reports',open,'Needs review or repair'],['Machines down',down,'Currently unusable'],[`${year} repair cost`,money(cost),'Parts + external service'],['Lifetime recorded',money(all),`${repairs.length} repair records`]].map(x=>`<div class="stat"><div class="value">${x[1]}</div><div class="label">${x[0]}</div><div class="sub">${x[2]}</div></div>`).join('')}
function renderDashboard(){if(!staff)return;const rank={Critical:4,High:3,Medium:2,Low:1},open=reports.filter(r=>r.status!=='Resolved').sort((a,b)=>(rank[b.urgency]-rank[a.urgency])||(toDate(b.createdAt)-toDate(a.createdAt))).slice(0,6);$('#openIssues').innerHTML=open.length?open.map(r=>`<div class="issue-row"><div><div class="row-title">${esc(machine(r.machineId).name)}</div><div class="row-meta">${date(r.createdAt)} · ${esc(r.issue)}</div></div>${badge(r.urgency)}</div>`).join(''):'<div class="empty">No open issues.</div>';const ids=[...new Set(reports.filter(r=>r.status!=='Resolved').map(r=>r.machineId))];$('#machineAttention').innerHTML=ids.length?ids.map(id=>{const m=machine(id),rs=reports.filter(r=>r.machineId===id&&r.status!=='Resolved');return `<div class="attention-row"><div><div class="row-title">${esc(m.name)}</div><div class="row-meta">${esc(m.room||'')} · ${rs.length} open report${rs.length===1?'':'s'}</div></div>${badge(rs.some(r=>r.usable==='No')?'Down':'Attention')}</div>`}).join(''):'<div class="empty">All machines clear.</div>'}
function renderPublicMachines(){const list=machines.length?machines:starterMachines;$('#publicMachines').innerHTML=list.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(m=>`<article class="machine-card"><h3>${esc(m.name)}</h3><div class="machine-id">${esc(m.id)}</div><div class="machine-meta"><div><span>Location:</span> ${esc(m.room||'—')}</div><div><span>Direct tutorials:</span> ${tutorialsForMachine(m).length}</div></div><div class="machine-actions"><button class="btn primary small" onclick="window.reportMachine('${esc(m.id)}')">Report problem</button><button class="btn secondary small" onclick="window.showMachineTutorials('${esc(m.tutorialEquipment||'')}')">Tutorials</button></div></article>`).join('')||'<div class="empty">No machines configured.</div>'}
window.reportMachine=id=>{const url=new URL(location.href);url.searchParams.set('machine',id);url.hash='report';location.href=url.toString()};window.showMachineTutorials=eq=>{showView('tutorials');$('#tutorialEquipment').value=[...$('#tutorialEquipment').options].some(o=>o.value===eq)?eq:'All';renderTutorials()};

function reportTable(){if(!staff)return;const status=$('#reportStatusFilter').value,q=($('#reportSearch').value||'').toLowerCase();const list=reports.filter(r=>(status==='All'||r.status===status)&&(!q||[r.id,machine(r.machineId).name,r.issue,r.contact].join(' ').toLowerCase().includes(q)));$('#reportsTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Machine</th><th>Urgency</th><th>Issue</th><th>Status</th><th></th></tr></thead><tbody>${list.map(r=>`<tr><td>${date(r.createdAt)}</td><td>${esc(machine(r.machineId).name)}</td><td>${badge(r.urgency)}</td><td>${esc(r.issue)}</td><td>${badge(r.status)}</td><td><button class="text-btn" onclick="window.manageReport('${esc(r.id)}')">Manage</button></td></tr>`).join('')}</tbody></table></div>`;if(!list.length)$('#reportsTable').innerHTML='<div class="empty">No matching reports.</div>'}
$('#reportStatusFilter').onchange=reportTable;$('#reportSearch').oninput=reportTable;
window.manageReport=id=>{const r=reports.find(x=>x.id===id);if(!r)return;$('#modalBody').innerHTML=`<h2>${esc(machine(r.machineId).name)}</h2><p>${badge(r.urgency)} ${badge(r.status)}</p><p><strong>Issue</strong><br>${esc(r.issue)}</p><p><strong>Fixes tried</strong><br>${esc(r.attempted||'None entered')}</p><p><strong>Contact</strong><br>${esc(r.contact||'Not provided')}</p><div class="form-grid"><label>Status<select id="manageStatus"><option>Open</option><option>Diagnosing</option><option>Waiting for Part</option><option>Resolved</option></select></label><div class="form-actions"><button type="button" class="btn secondary" onclick="window.addRepairFor('${esc(r.id)}')">Add repair/cost</button><button type="button" class="btn primary" onclick="window.saveReportStatus('${esc(r.id)}')">Save status</button></div></div>`;$('#manageStatus').value=r.status;$('#modal').showModal()};
window.saveReportStatus=async id=>{await updateDoc(doc(fs,'reports',id),{status:$('#manageStatus').value,updatedAt:serverTimestamp()});$('#modal').close();toast('Report status updated')};

function renderMachines(){if(!staff)return;$('#machineCards').innerHTML=machines.map(m=>{const rs=reports.filter(r=>r.machineId===m.id),cost=repairs.filter(r=>r.machineId===m.id).reduce((a,r)=>a+totalRepair(r),0),ts=tutorialsForMachine(m);return `<article class="machine-card"><div class="machine-top"><div><h3>${esc(m.name)}</h3><div class="machine-id">${esc(m.id)}</div></div>${badge(m.status||'Operational')}</div><div class="machine-meta"><div><span>Type:</span> ${esc(m.category||'—')}</div><div><span>Location:</span> ${esc(m.room||'—')}</div><div><span>Tutorial set:</span> ${esc(m.tutorialEquipment||'—')} (${ts.length})</div><div><span>Reports:</span> ${rs.length}</div><div><span>Recorded repair cost:</span> ${money(cost)}</div></div><div class="machine-actions"><button class="btn secondary small" onclick="window.copyMaintenanceLink('${esc(m.id)}')">Copy Maintenance Link</button><button class="btn secondary small" onclick="window.editMachine('${esc(m.id)}')">Edit</button></div></article>`}).join('')||'<div class="empty">No machines configured. Use “Add Machine” or seed starter records from Settings.</div>'}
window.copyMaintenanceLink=id=>{const url=new URL(location.href);url.search='';url.searchParams.set('machine',id);url.hash='report';navigator.clipboard?.writeText(url.toString());toast('Maintenance link copied for Linktree')};
function machineModal(existing){const m=existing||{id:'',name:'',category:'',room:'',manufacturer:'',model:'',serial:'',purchaseDate:'',purchaseCost:0,status:'Operational',tutorialEquipment:''};const eq=[...new Set(tutorials.flatMap(t=>tutorialEquipments(t)))].sort();$('#modalBody').innerHTML=`<h2>${existing?'Edit':'Add'} machine</h2><div class="form-grid"><label>Stable ID<input id="mId" value="${esc(m.id)}" ${existing?'disabled':''}></label><label>Name<input id="mName" value="${esc(m.name)}"></label><label>Category<input id="mCategory" value="${esc(m.category||'')}"></label><label>Room<input id="mRoom" value="${esc(m.room||'')}"></label><label>Manufacturer<input id="mManufacturer" value="${esc(m.manufacturer||'')}"></label><label>Model<input id="mModel" value="${esc(m.model||'')}"></label><label>Serial<input id="mSerial" value="${esc(m.serial||'')}"></label><label>Purchase cost<input id="mCost" type="number" step="0.01" value="${Number(m.purchaseCost||0)}"></label><label class="full">Tutorial / equipment set<select id="mTutorial"><option value="">None</option>${eq.map(x=>`<option ${x===m.tutorialEquipment?'selected':''}>${esc(x)}</option>`).join('')}</select></label><div class="form-actions full"><button type="button" class="btn primary" onclick="window.saveMachine('${existing?esc(m.id):''}')">Save machine</button></div></div>`;$('#modal').showModal()}
$('#addMachine').onclick=()=>machineModal();window.editMachine=id=>machineModal(machines.find(m=>m.id===id));window.saveMachine=async original=>{if(!staff)return;const id=original||slug($('#mId').value);const name=$('#mName').value.trim();if(!id||!name)return toast('Machine ID and name are required');const obj={name,category:$('#mCategory').value.trim(),room:$('#mRoom').value.trim(),manufacturer:$('#mManufacturer').value.trim(),model:$('#mModel').value.trim(),serial:$('#mSerial').value.trim(),purchaseCost:Number($('#mCost').value||0),status:original?(machine(original).status||'Operational'):'Operational',tutorialEquipment:$('#mTutorial').value,updatedAt:serverTimestamp()};await setDoc(doc(fs,'machines',id),obj,{merge:true});$('#modal').close();toast('Machine saved')};

function renderCosts(){if(!staff)return;const year=new Date().getFullYear(),thisYear=repairs.filter(r=>toDate(r.date).getFullYear()===year).reduce((a,r)=>a+totalRepair(r),0),all=repairs.reduce((a,r)=>a+totalRepair(r),0),days=repairs.reduce((a,r)=>a+Number(r.downtimeDays||0),0);$('#costStats').innerHTML=[['This year',money(thisYear),'Recorded repair spend'],['All recorded',money(all),'Parts + service'],['Downtime',`${days} days`,'Across repair records'],['Repair events',repairs.length,'Maintenance records']].map(x=>`<div class="stat"><div class="value">${x[1]}</div><div class="label">${x[0]}</div><div class="sub">${x[2]}</div></div>`).join('');$('#repairsTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Machine</th><th>Repair / resolution</th><th>Part</th><th>Technician</th><th>Downtime</th><th>Cost</th></tr></thead><tbody>${repairs.map(r=>`<tr><td>${date(r.date)}</td><td>${esc(machine(r.machineId).name)}</td><td>${esc(r.resolution)}</td><td>${esc(r.part||'—')}</td><td>${esc(r.technician||'—')}</td><td>${Number(r.downtimeDays||0)} d</td><td><strong>${money(totalRepair(r))}</strong></td></tr>`).join('')}</tbody></table></div>`}
function repairModal(reportId=''){const r=reports.find(x=>x.id===reportId);$('#modalBody').innerHTML=`<h2>Add repair / cost</h2><div class="form-grid"><label class="full">Machine<select id="rMachine">${machines.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></label><label>Related report<select id="rReport"><option value="">None</option>${reports.map(x=>`<option value="${esc(x.id)}">${esc(x.id.slice(0,8))} — ${esc(x.issue.slice(0,45))}</option>`).join('')}</select></label><label>Technician<input id="rTech" placeholder="Name or team"></label><label class="full">Resolution / work performed<textarea id="rResolution" rows="3"></textarea></label><label>Part / item<input id="rPart"></label><label>Parts cost<input id="rParts" type="number" step="0.01" value="0"></label><label>External service cost<input id="rService" type="number" step="0.01" value="0"></label><label>Labor hours<input id="rHours" type="number" step="0.25" value="0"></label><label>Downtime days<input id="rDown" type="number" step="0.5" value="0"></label><div class="form-actions full"><button type="button" class="btn primary" onclick="window.saveRepair()">Save repair</button></div></div>`;if(r){$('#rMachine').value=r.machineId;$('#rReport').value=r.id}$('#modal').showModal()}
$('#addRepair').onclick=()=>repairModal();window.addRepairFor=id=>repairModal(id);window.saveRepair=async()=>{const reportId=$('#rReport').value,machineId=$('#rMachine').value,resolution=$('#rResolution').value.trim();if(!resolution)return toast('Please enter the work performed');await addDoc(collection(fs,'repairs'),{reportId,machineId,date:serverTimestamp(),technician:$('#rTech').value.trim(),resolution,part:$('#rPart').value.trim(),partsCost:Number($('#rParts').value||0),serviceCost:Number($('#rService').value||0),laborHours:Number($('#rHours').value||0),downtimeDays:Number($('#rDown').value||0)});if(reportId)await updateDoc(doc(fs,'reports',reportId),{status:'Resolved',updatedAt:serverTimestamp()});$('#modal').close();toast('Repair record saved')};

function csvCell(v){const s=v?.toDate?v.toDate().toISOString():String(v??'');return `"${s.replaceAll('"','""')}"`}
function download(name,text,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCsv(type){let headers,rows;if(type==='reports'){headers=['Report ID','Date','Machine ID','Machine','Room','Urgency','Usable','Issue','Fixes Tried','Preferred Contact','Resource','Status'];rows=reports.map(r=>[r.id,r.createdAt,r.machineId,machine(r.machineId).name,machine(r.machineId).room,r.urgency,r.usable,r.issue,r.attempted,r.contact,r.resource,r.status])}if(type==='machines'){headers=['Machine ID','Name','Category','Room','Manufacturer','Model','Serial','Purchase Cost','Status','Tutorial Equipment'];rows=machines.map(m=>[m.id,m.name,m.category,m.room,m.manufacturer,m.model,m.serial,m.purchaseCost,m.status,m.tutorialEquipment])}if(type==='repairs'){headers=['Repair ID','Date','Report ID','Machine ID','Machine','Technician','Resolution','Part','Parts Cost','Service Cost','Total Cost','Labor Hours','Downtime Days'];rows=repairs.map(r=>[r.id,r.date,r.reportId,r.machineId,machine(r.machineId).name,r.technician,r.resolution,r.part,r.partsCost,r.serviceCost,totalRepair(r),r.laborHours,r.downtimeDays])}download(`TAD-Lab-${type}-${new Date().toISOString().slice(0,10)}.csv`,[headers,...rows].map(row=>row.map(csvCell).join(',')).join('\n'))}
$$('[data-export]').forEach(b=>b.onclick=()=>exportCsv(b.dataset.export));$('#backupJson').onclick=()=>download(`TAD-Lab-Full-Backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({machines,reports,repairs},(k,v)=>v?.toDate?v.toDate().toISOString():v,2),'application/json');

async function seedMachines(){if(!staff||!fs)return;const snap=await getDocs(collection(fs,'machines'));if(!snap.empty&&!confirm('Machines already exist. Add/update the starter machine records anyway?'))return;const batch=writeBatch(fs);starterMachines.forEach(m=>{const {id,...data}=m;batch.set(doc(fs,'machines',id),{...data,createdAt:serverTimestamp()},{merge:true})});await batch.commit();toast('Starter machine records added')}
function renderSettingsExtras(){if(!staff||!configured)return;const info=$('#firebaseInfo');if(!$('#seedMachinesBtn'))info.insertAdjacentHTML('beforeend','<button id="seedMachinesBtn" class="btn secondary">Add starter machine records</button>');$('#seedMachinesBtn')?.addEventListener('click',seedMachines,{once:true})}

function renderAll(){renderStaffVisibility();renderConnection();renderReportForm();renderTutorials();renderPublicMachines();renderMachineResourcePanel();if(staff){renderStats();renderDashboard();reportTable();renderMachines();renderCosts();renderSettingsExtras()}}

await loadTutorials();await initFirebase();renderAll();
const initial=new URLSearchParams(location.search).has('machine')?'report':(location.hash.replace('#','')||'dashboard');showView(initial);
