const STORAGE_KEY='tadLabManagerPrototypeV01';
const now=()=>new Date();
const isoDaysAgo=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toISOString()};
const seed={
 machines:[
  {id:'3dp-ultimaker-s5-01',name:'Ultimaker S5 #1',category:'3D Printer',room:'3D Print Lab',manufacturer:'Ultimaker',model:'S5',serial:'S5-DEMO-001',purchaseDate:'2022-08-01',purchaseCost:6995,status:'Operational',stakeholders:['eric.carlson.2@bemidjistate.edu','chase.cornell@bemidjistate.edu']},
  {id:'3dp-bambu-x1c-01',name:'Bambu Lab X1 Carbon #1',category:'3D Printer',room:'3D Print Lab',manufacturer:'Bambu Lab',model:'X1 Carbon',serial:'X1C-DEMO-101',purchaseDate:'2024-02-15',purchaseCost:1449,status:'Operational',stakeholders:['eric.carlson.2@bemidjistate.edu','chase.cornell@bemidjistate.edu']},
  {id:'laser-epilog-fusion-01',name:'Epilog Fusion Pro Laser',category:'Laser Cutter',room:'Maker Lab',manufacturer:'Epilog',model:'Fusion Pro',serial:'EPI-DEMO-301',purchaseDate:'2021-06-01',purchaseCost:34500,status:'Needs Attention',stakeholders:['eric.carlson.2@bemidjistate.edu','Mitchell.Blessing@bemidjistate.edu','chase.cornell@bemidjistate.edu']},
  {id:'cnc-shopbot-01',name:'ShopBot CNC',category:'CNC Router',room:'BH 126',manufacturer:'ShopBot',model:'PRTalpha',serial:'SHOP-DEMO-126',purchaseDate:'2019-08-20',purchaseCost:18900,status:'Operational',stakeholders:['eric.carlson.2@bemidjistate.edu','chase.cornell@bemidjistate.edu']}
 ],
 reports:[
  {id:'R-1004',machineId:'laser-epilog-fusion-01',createdAt:isoDaysAgo(0),urgency:'High',usable:'No',issue:'Laser powers on but will not fire during job.',attempted:'Restarted machine and checked lid interlocks.',contact:'Student worker',resource:'',status:'Open',notified:true},
  {id:'R-1003',machineId:'3dp-ultimaker-s5-01',createdAt:isoDaysAgo(2),urgency:'Medium',usable:'Partially',issue:'Filament slipping during longer prints.',attempted:'Reloaded filament and cleaned feeder.',contact:'',resource:'',status:'Diagnosing',notified:true},
  {id:'R-1002',machineId:'cnc-shopbot-01',createdAt:isoDaysAgo(9),urgency:'High',usable:'No',issue:'X-axis limit switch error at startup.',attempted:'Cleared obstruction and restarted.',contact:'',resource:'',status:'Resolved',notified:true},
  {id:'R-1001',machineId:'3dp-bambu-x1c-01',createdAt:isoDaysAgo(15),urgency:'Low',usable:'Yes',issue:'Build plate adhesion inconsistent.',attempted:'Washed plate.',contact:'',resource:'',status:'Resolved',notified:false}
 ],
 repairs:[
  {id:'M-501',reportId:'R-1002',machineId:'cnc-shopbot-01',date:isoDaysAgo(7),technician:'Lab staff',resolution:'Replaced damaged X-axis limit switch.',part:'Limit switch',partsCost:31.42,serviceCost:0,laborHours:0.75,downtimeDays:2},
  {id:'M-500',reportId:'R-1001',machineId:'3dp-bambu-x1c-01',date:isoDaysAgo(14),technician:'Student worker',resolution:'Cleaned plate and updated handling instructions.',part:'',partsCost:0,serviceCost:0,laborHours:0.25,downtimeDays:0}
 ],
 settings:{nextReport:1005,nextRepair:502}
};
let db=load();
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db));renderAll()}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))}
function date(v){return new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function machine(id){return db.machines.find(m=>m.id===id)||{name:'Unknown Machine',room:'',stakeholders:[]}}
function badge(v){return `<span class="badge ${String(v).toLowerCase().replaceAll(' ','')}">${esc(v)}</span>`}
function totalRepair(r){return Number(r.partsCost||0)+Number(r.serviceCost||0)}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

const titles={dashboard:['Dashboard','Lab equipment status, issues, repairs, and costs.'],report:['Report a Problem','Submit a machine issue from a QR code or the app.'],reports:['Reports','Review and manage issue history.'],machines:['Machines','Equipment inventory, QR links, and notification routing.'],costs:['Costs & Repairs','Track repair history and lifetime equipment costs.'],export:['Export / Backup','Keep your records portable and spreadsheet-friendly.'],settings:['Settings','Prototype configuration and production roadmap.']};
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelector(`#view-${v}`).classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelector('#pageTitle').textContent=titles[v][0];document.querySelector('#pageSubtitle').textContent=titles[v][1];document.querySelector('.sidebar').classList.remove('open');history.replaceState(null,'',v==='report'&&new URLSearchParams(location.search).has('machine')?location.href.split('#')[0]:location.pathname+'#'+v)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));document.querySelector('#quickReport').onclick=()=>showView('report');document.querySelector('#mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');

function renderStats(){const open=db.reports.filter(r=>r.status!=='Resolved').length;const down=new Set(db.reports.filter(r=>r.status!=='Resolved'&&r.usable==='No').map(r=>r.machineId)).size;const year=now().getFullYear();const cost=db.repairs.filter(r=>new Date(r.date).getFullYear()===year).reduce((a,r)=>a+totalRepair(r),0);const all=db.repairs.reduce((a,r)=>a+totalRepair(r),0);document.querySelector('#statsGrid').innerHTML=[['Open reports',open,'Needs review or repair'],['Machines down',down,'Currently unusable'],[`${year} repair cost`,money(cost),'Parts + external service'],['Lifetime recorded',money(all),`${db.repairs.length} repair records`]].map(x=>`<div class="stat"><div class="value">${x[1]}</div><div class="label">${x[0]}</div><div class="sub">${x[2]}</div></div>`).join('')}
function renderDashboard(){const rank={Critical:4,High:3,Medium:2,Low:1};const open=db.reports.filter(r=>r.status!=='Resolved').sort((a,b)=>(rank[b.urgency]-rank[a.urgency])||(new Date(b.createdAt)-new Date(a.createdAt))).slice(0,6);document.querySelector('#openIssues').innerHTML=open.length?open.map(r=>`<div class="issue-row"><div><div class="row-title">${esc(machine(r.machineId).name)}</div><div class="row-meta">${date(r.createdAt)} · ${esc(r.issue)}</div></div>${badge(r.urgency)}</div>`).join(''):'<div class="empty">No open issues.</div>';
 const ids=[...new Set(db.reports.filter(r=>r.status!=='Resolved').map(r=>r.machineId))];document.querySelector('#machineAttention').innerHTML=ids.length?ids.map(id=>{const m=machine(id), rs=db.reports.filter(r=>r.machineId===id&&r.status!=='Resolved');return `<div class="attention-row"><div><div class="row-title">${esc(m.name)}</div><div class="row-meta">${esc(m.room)} · ${rs.length} open report${rs.length===1?'':'s'}</div></div>${badge(rs.some(r=>r.usable==='No')?'Down':'Attention')}</div>`}).join(''):'<div class="empty">All machines clear.</div>';
 document.querySelector('#recentCosts').innerHTML=db.repairs.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5).map(r=>`<div class="cost-row"><div><div class="row-title">${esc(machine(r.machineId).name)} — ${esc(r.resolution)}</div><div class="row-meta">${date(r.date)} · ${esc(r.technician)}</div></div><strong>${money(totalRepair(r))}</strong></div>`).join('')||'<div class="empty">No repair costs recorded.</div>'}
function renderReportForm(){const sel=document.querySelector('#reportMachine');const current=sel.value;sel.innerHTML=db.machines.map(m=>`<option value="${m.id}">${esc(m.name)} — ${esc(m.room)}</option>`).join('');const q=new URLSearchParams(location.search).get('machine');sel.value=q&&db.machines.some(m=>m.id===q)?q:(current||db.machines[0]?.id||'');updatePreview()}
function updatePreview(){const m=machine(document.querySelector('#reportMachine').value);const urgency=document.querySelector('#urgency').value;const issue=document.querySelector('#issue').value||'[student description]';const attempted=document.querySelector('#attempted').value||'[none entered]';document.querySelector('#notificationPreview').textContent=`TO\n${m.stakeholders.join('\n')||'[No stakeholders assigned]'}\n\nSUBJECT\n${m.name}: ${urgency} technical difficulty\n\nBODY\nUrgency: ${urgency}\nMachine: ${m.name}\nRoom: ${m.room}\nIssue: ${issue}\nFixes tried: ${attempted}\nPreferred contact: ${document.querySelector('#contact').value||'[not provided]'}\nResource: ${document.querySelector('#resource').value||'[none]'}\n\nA permanent report record will be created.`}
['reportMachine','urgency','issue','attempted','contact','resource'].forEach(id=>document.querySelector('#'+id).addEventListener('input',updatePreview));
document.querySelector('#reportForm').onsubmit=e=>{e.preventDefault();const r={id:`R-${db.settings.nextReport++}`,machineId:document.querySelector('#reportMachine').value,createdAt:new Date().toISOString(),urgency:document.querySelector('#urgency').value,usable:document.querySelector('#usable').value,issue:document.querySelector('#issue').value.trim(),attempted:document.querySelector('#attempted').value.trim(),contact:document.querySelector('#contact').value.trim(),resource:document.querySelector('#resource').value.trim(),status:'Open',notified:document.querySelector('#notify').checked};db.reports.unshift(r);const m=machine(r.machineId);if(r.usable==='No')m.status='Needs Attention';save();e.target.reset();renderReportForm();toast(`Report ${r.id} saved${r.notified?' — notification simulated':''}`);showView('reports')};

function reportTable(){const status=document.querySelector('#reportStatusFilter').value.toLowerCase(),q=document.querySelector('#reportSearch').value.toLowerCase();let rows=db.reports.filter(r=>(status==='all'||r.status.toLowerCase()===status)&&(!q||[r.id,r.issue,r.status,r.urgency,machine(r.machineId).name].join(' ').toLowerCase().includes(q)));document.querySelector('#reportsTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Date</th><th>Machine</th><th>Issue</th><th>Urgency</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.id}</td><td>${date(r.createdAt)}</td><td><strong>${esc(machine(r.machineId).name)}</strong><br><span class="row-meta">${esc(machine(r.machineId).room)}</span></td><td>${esc(r.issue)}</td><td>${badge(r.urgency)}</td><td>${badge(r.status)}</td><td><button class="text-btn" onclick="openReport('${r.id}')">Open</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No matching reports.</td></tr>'}</tbody></table></div>`}
document.querySelector('#reportStatusFilter').onchange=reportTable;document.querySelector('#reportSearch').oninput=reportTable;
window.openReport=id=>{const r=db.reports.find(x=>x.id===id),m=machine(r.machineId);const reps=db.repairs.filter(x=>x.reportId===id);document.querySelector('#modalBody').innerHTML=`<h2>${r.id}: ${esc(m.name)}</h2><p>${badge(r.urgency)} ${badge(r.status)}</p><p><strong>Reported:</strong> ${date(r.createdAt)}<br><strong>Usable:</strong> ${esc(r.usable)}<br><strong>Issue:</strong> ${esc(r.issue)}<br><strong>Fixes tried:</strong> ${esc(r.attempted||'None')}<br><strong>Contact:</strong> ${esc(r.contact||'Not provided')}</p><label>Status<select id="modalStatus"><option>Open</option><option>Diagnosing</option><option>Waiting for Part</option><option>Resolved</option></select></label><div class="form-actions" style="margin-top:16px"><button type="button" class="btn secondary" onclick="addRepairFor('${id}')">Add repair/cost</button><button type="button" class="btn primary" onclick="saveReportStatus('${id}')">Save status</button></div>${reps.length?`<hr><h3>Repair history</h3>${reps.map(x=>`<p>${date(x.date)} — ${esc(x.resolution)} <strong>${money(totalRepair(x))}</strong></p>`).join('')}`:''}`;document.querySelector('#modalStatus').value=r.status;document.querySelector('#modal').showModal()}
window.saveReportStatus=id=>{const r=db.reports.find(x=>x.id===id);r.status=document.querySelector('#modalStatus').value;if(r.status==='Resolved'){const hasOpen=db.reports.some(x=>x.machineId===r.machineId&&x.id!==r.id&&x.status!=='Resolved');if(!hasOpen)machine(r.machineId).status='Operational'}save();document.querySelector('#modal').close();toast('Report status updated')}

function renderMachines(){document.querySelector('#machineCards').innerHTML=db.machines.map(m=>{const reports=db.reports.filter(r=>r.machineId===m.id),cost=db.repairs.filter(r=>r.machineId===m.id).reduce((a,r)=>a+totalRepair(r),0);return `<article class="machine-card"><div class="machine-top"><div><h3>${esc(m.name)}</h3><div class="machine-id">${esc(m.id)}</div></div>${badge(m.status)}</div><div class="machine-meta"><div><span>Type:</span> ${esc(m.category)}</div><div><span>Location:</span> ${esc(m.room)}</div><div><span>Model:</span> ${esc(m.manufacturer)} ${esc(m.model)}</div><div><span>Reports:</span> ${reports.length}</div><div><span>Recorded repair cost:</span> ${money(cost)}</div></div><div class="machine-actions"><button class="btn secondary small" onclick="copyQrLink('${m.id}')">Copy QR Link</button><button class="btn secondary small" onclick="editMachine('${m.id}')">Edit</button></div></article>`}).join('')}
window.copyQrLink=id=>{const url=new URL(location.href);url.hash='report';url.searchParams.set('machine',id);navigator.clipboard?.writeText(url.toString());toast('Machine report link copied')}
function machineModal(existing){const m=existing||{id:'',name:'',category:'',room:'',manufacturer:'',model:'',serial:'',purchaseDate:'',purchaseCost:'',status:'Operational',stakeholders:[]};document.querySelector('#modalBody').innerHTML=`<h2>${existing?'Edit':'Add'} machine</h2><div class="form-grid"><label>Stable ID<input id="mId" value="${esc(m.id)}" ${existing?'disabled':''}></label><label>Name<input id="mName" value="${esc(m.name)}"></label><label>Category<input id="mCategory" value="${esc(m.category)}"></label><label>Room<input id="mRoom" value="${esc(m.room)}"></label><label>Manufacturer<input id="mManufacturer" value="${esc(m.manufacturer)}"></label><label>Model<input id="mModel" value="${esc(m.model)}"></label><label>Serial<input id="mSerial" value="${esc(m.serial)}"></label><label>Purchase cost<input id="mCost" type="number" step="0.01" value="${esc(m.purchaseCost)}"></label><label class="full">Stakeholder emails (comma separated)<textarea id="mStake">${esc(m.stakeholders.join(', '))}</textarea></label><div class="form-actions full"><button type="button" class="btn primary" onclick="saveMachine('${existing?m.id:''}')">Save machine</button></div></div>`;document.querySelector('#modal').showModal()}
document.querySelector('#addMachine').onclick=()=>machineModal();window.editMachine=id=>machineModal(db.machines.find(m=>m.id===id));window.saveMachine=original=>{const id=original||document.querySelector('#mId').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-');if(!id||!document.querySelector('#mName').value.trim())return toast('Machine ID and name are required');const obj={id,name:document.querySelector('#mName').value.trim(),category:document.querySelector('#mCategory').value.trim(),room:document.querySelector('#mRoom').value.trim(),manufacturer:document.querySelector('#mManufacturer').value.trim(),model:document.querySelector('#mModel').value.trim(),serial:document.querySelector('#mSerial').value.trim(),purchaseDate:'',purchaseCost:Number(document.querySelector('#mCost').value||0),status:original?machine(original).status:'Operational',stakeholders:document.querySelector('#mStake').value.split(',').map(x=>x.trim()).filter(Boolean)};if(original)Object.assign(machine(original),obj);else db.machines.push(obj);save();document.querySelector('#modal').close();toast('Machine saved')}

function renderCosts(){const year=now().getFullYear(),thisYear=db.repairs.filter(r=>new Date(r.date).getFullYear()===year).reduce((a,r)=>a+totalRepair(r),0),all=db.repairs.reduce((a,r)=>a+totalRepair(r),0),days=db.repairs.reduce((a,r)=>a+Number(r.downtimeDays||0),0);document.querySelector('#costStats').innerHTML=[['This year',money(thisYear),'Recorded repair spend'],['All recorded',money(all),'Parts + service'],['Downtime',`${days} days`,'Across completed repairs'],['Repair events',db.repairs.length,'Maintenance records']].map(x=>`<div class="stat"><div class="value">${x[1]}</div><div class="label">${x[0]}</div><div class="sub">${x[2]}</div></div>`).join('');document.querySelector('#repairsTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Machine</th><th>Repair / resolution</th><th>Part</th><th>Technician</th><th>Downtime</th><th>Cost</th></tr></thead><tbody>${db.repairs.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(r=>`<tr><td>${date(r.date)}</td><td>${esc(machine(r.machineId).name)}</td><td>${esc(r.resolution)}</td><td>${esc(r.part||'—')}</td><td>${esc(r.technician||'—')}</td><td>${Number(r.downtimeDays||0)} d</td><td><strong>${money(totalRepair(r))}</strong></td></tr>`).join('')}</tbody></table></div>`}
function repairModal(reportId=''){const r=db.reports.find(x=>x.id===reportId);document.querySelector('#modalBody').innerHTML=`<h2>Add repair / cost</h2><div class="form-grid"><label class="full">Machine<select id="rMachine">${db.machines.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><label>Related report<select id="rReport"><option value="">None</option>${db.reports.map(x=>`<option value="${x.id}">${x.id} — ${esc(x.issue.slice(0,45))}</option>`).join('')}</select></label><label>Technician<input id="rTech" placeholder="Name or team"></label><label class="full">Resolution / work performed<textarea id="rResolution" rows="3"></textarea></label><label>Part / item<input id="rPart"></label><label>Parts cost<input id="rParts" type="number" step="0.01" value="0"></label><label>External service cost<input id="rService" type="number" step="0.01" value="0"></label><label>Labor hours<input id="rHours" type="number" step="0.25" value="0"></label><label>Downtime days<input id="rDown" type="number" step="0.5" value="0"></label><div class="form-actions full"><button type="button" class="btn primary" onclick="saveRepair()">Save repair</button></div></div>`;if(r){document.querySelector('#rMachine').value=r.machineId;document.querySelector('#rReport').value=r.id}document.querySelector('#modal').showModal()}
document.querySelector('#addRepair').onclick=()=>repairModal();window.addRepairFor=id=>repairModal(id);window.saveRepair=()=>{const x={id:`M-${db.settings.nextRepair++}`,reportId:document.querySelector('#rReport').value,machineId:document.querySelector('#rMachine').value,date:new Date().toISOString(),technician:document.querySelector('#rTech').value.trim(),resolution:document.querySelector('#rResolution').value.trim(),part:document.querySelector('#rPart').value.trim(),partsCost:Number(document.querySelector('#rParts').value||0),serviceCost:Number(document.querySelector('#rService').value||0),laborHours:Number(document.querySelector('#rHours').value||0),downtimeDays:Number(document.querySelector('#rDown').value||0)};if(!x.resolution)return toast('Please enter the work performed');db.repairs.unshift(x);if(x.reportId){const rep=db.reports.find(r=>r.id===x.reportId);if(rep)rep.status='Resolved';const hasOpen=db.reports.some(r=>r.machineId===x.machineId&&r.status!=='Resolved');if(!hasOpen)machine(x.machineId).status='Operational'}save();document.querySelector('#modal').close();toast('Repair record saved')}

function renderRouting(){document.querySelector('#routingList').innerHTML=db.machines.map(m=>`<div class="routing"><strong>${esc(m.name)}</strong><span>${m.stakeholders.map(esc).join(' · ')||'No stakeholders assigned'}</span></div>`).join('')}
function csvCell(v){const s=String(v??'');return `"${s.replaceAll('"','""')}"`}
function download(name,text,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCsv(type){let headers,rows;if(type==='reports'){headers=['Report ID','Date','Machine ID','Machine','Room','Urgency','Usable','Issue','Fixes Tried','Preferred Contact','Resource','Status','Notification'];rows=db.reports.map(r=>[r.id,r.createdAt,r.machineId,machine(r.machineId).name,machine(r.machineId).room,r.urgency,r.usable,r.issue,r.attempted,r.contact,r.resource,r.status,r.notified?'Yes':'No'])}if(type==='machines'){headers=['Machine ID','Name','Category','Room','Manufacturer','Model','Serial','Purchase Date','Purchase Cost','Status','Stakeholders'];rows=db.machines.map(m=>[m.id,m.name,m.category,m.room,m.manufacturer,m.model,m.serial,m.purchaseDate,m.purchaseCost,m.status,m.stakeholders.join('; ')])}if(type==='repairs'){headers=['Repair ID','Date','Report ID','Machine ID','Machine','Technician','Resolution','Part','Parts Cost','Service Cost','Total Cost','Labor Hours','Downtime Days'];rows=db.repairs.map(r=>[r.id,r.date,r.reportId,r.machineId,machine(r.machineId).name,r.technician,r.resolution,r.part,r.partsCost,r.serviceCost,totalRepair(r),r.laborHours,r.downtimeDays])}download(`TAD-Lab-${type}-${new Date().toISOString().slice(0,10)}.csv`,[headers,...rows].map(row=>row.map(csvCell).join(',')).join('\n'))}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportCsv(b.dataset.export));document.querySelector('#backupJson').onclick=()=>download(`TAD-Lab-Full-Backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(db,null,2),'application/json');document.querySelector('#restoreJson').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{db=JSON.parse(reader.result);save();toast('Backup restored')}catch{toast('That backup could not be read')}};reader.readAsText(f)};document.querySelector('#resetDemo').onclick=()=>{if(confirm('Replace current prototype data with the original demo data?')){db=structuredClone(seed);save();toast('Demo data restored')}};
function renderAll(){renderStats();renderDashboard();renderReportForm();reportTable();renderMachines();renderCosts();renderRouting()}
renderAll();
const initial=new URLSearchParams(location.search).has('machine')?'report':(location.hash.replace('#','')||'dashboard');if(titles[initial])showView(initial);
